# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       expat
Summary:    An XML parser library
Version:    2.1.0
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.libexpat.org/
Source0:    http://download.sourceforge.net/expat/expat-%{version}.tar.gz
Source100:  expat.yaml
Patch0:     expat-aarch64.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  libtool


%description
This is expat, the C library for parsing XML, written by James Clark. Expat
is a stream oriented XML parser. This means that you register handlers with
the parser prior to starting the parse. These handlers are called when the
parser discovers the associated structures in the document being parsed. A
start tag is an example of the kind of structures for which you may
register handlers.



%package doc
Summary:    Documentation for the expat package
Group:      Development/Documentation
Requires:   %{name} = %{version}-%{release}
Requires:   expat = %{version}-%{release}

%description doc
Documentation for the expat package.

%package devel
Summary:    Libraries and header files to develop applications using expat
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   expat = %{version}-%{release}

%description devel
The expat-devel package contains the libraries, include files and documentation
to develop XML applications with expat.



%prep
%setup -q -n %{name}-%{version}
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
rm -rf autom4te*.cache
cp `aclocal --print-ac-dir`/libtool.m4 conftools || exit 1
libtoolize --copy --force --automake && aclocal && autoheader && autoconf
export CFLAGS="$RPM_OPT_FLAGS -fPIC"
# << build pre

%configure --disable-static \
    --libdir=/%{_libdir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
rm -f examples/*.dsp
chmod 644 README COPYING Changes doc/* examples/*
# << install pre
%make_install

# >> install post
# << install post
%check
# >> check
make check
# << check



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_bindir}/*
%{_libdir}/lib*.so.*
# << files


%files doc
%defattr(-,root,root,-)
# >> files doc
%doc %{_mandir}/*/*
%doc README
%doc Changes doc examples
# << files doc

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/lib*.so
%{_includedir}/*.h
%{_libdir}/pkgconfig/expat.pc
# << files devel

